# Generated by Django 2.1.5 on 2019-01-20 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgen', '0002_teaching'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teaching',
            new_name='Course',
        ),
    ]
