# Generated by Django 2.1.5 on 2019-01-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgen', '0005_auto_20190120_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='use',
            new_name='about',
        ),
    ]
