# Generated by Django 2.1.5 on 2019-01-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgen', '0006_auto_20190120_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about',
            new_name='user',
        ),
    ]
