# Generated by Django 2.1.5 on 2019-01-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgen', '0007_auto_20190120_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='your_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
