# Generated by Django 2.1.5 on 2019-01-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgen', '0008_profile_your_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='your_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
