# Generated by Django 2.1.5 on 2019-01-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgen', '0009_auto_20190124_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='your_url',
            new_name='already_have_a_website',
        ),
    ]
